backend:
  branch: main
  name: github
  open_authoring: true
  repo: moduon/oca-docs
  squash_merges: true
  use_graphql: true

media_folder: static/media
public_folder: /media
publish_mode: editorial_workflow

collections:
  - name: page
    label: Pages
    folder: content
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: module
    label: Modules
    folder: content/module
    slug: "{{ technical_name }}"
    fields:
      - { label: "Technical name", name: "slug", widget: "string" }
      - { label: "Human-readable name", name: "title", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown" }
      - { label: "Usage", name: "usage", widget: "markdown", required: false }
      - { label: "Context", name: "context", widget: "markdown", required: false }
      - { label: "Installation", name: "install", widget: "markdown", required: false }
      - label: "Configuration"
        name: "configure"
        widget: "markdown"
        required: false
