backend:
  branch: main
  name: github
  repo: moduon/oca-docs
  squash_merges: true
  use_graphql: true

media_folder: docs/img
public_folder: /img

collections:
  - name: page
    label: Pages
    folder: docs/page
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: module
    label: Modules
    folder: docs/module
    slug: "{{ technical_name }}"
    fields:
      - { label: "Technical name", name: "technical_name", widget: "string" }
      - { label: "Human-readable name", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
